### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by raphaelschwinger** [DBD-research-group/BirdSet#258]
We should use automatic code formatting to make our code pretty :-)

## Tasks

- [ ] configure formatter for vscode in [vscode workspace](https://code.visualstudio.com/docs/getstarted/settings#_workspace-settings)
- [ ] format all files

**Comment by reheinrich** [comment]
@raphaelschwinger , I use the [Black code formatter](https://pypi.org/project/black/) with the default settings. 
However, I do not work with VSCode but with PyCharm and could easily integrate it there.
